[package]
name = "kmeans"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
npyz = "0.8"
walkdir = "2"
rand = "0.8.5"
rayon = "1.10.0"
clap = { version = "4.5.6", features = ["derive"] }
